# A loadbalancer service configuration for the showcase API
apiVersion: v1
kind: Service
metadata:
  name: showcase-api-service
  labels:
    app: showcase-api-service
  namespace: showcase-api
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: showcase-api
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: LoadBalancer
  selector:
    app: showcase-api
  externalTrafficPolicy: Local
